title: Just a webpage
email: jordan.hugh@yahoo.com
description: "Nothing here, move along."
twitter_username: Jord4563
github_username:  Jord4563

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
