title: Jordan's Blog
email: jordan.hugh@yahoo.com
description: "Just my blog, I guess."
twitter_username: Jord4563
github_username:  Jord4563

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
